### ISSUE TITLE
Implement Lowering Platform stepper control with a Raspberry Pi

### ISSUE THREAD

**Issue by parham-sharaf** [SC-Robotics-2021/osiris_science#4]

**Comment by jasperdoan** [comment]
Written by @austinlake04 :

I'm running into an error when running the lowering platforn server node one the `consolidate_nodes` branch. This is refering to the node `lowering_platform_server.py` in the directiory: `src/science_servers/science_servers`. The class definition is abstracted and can be found in `template_servers.py` in the same referred to earlier. This earlier is related to the dependency `ticlib` and the error occurs when initializing the stepper motor driver's object as shown on line 159 in `template_servers.py`. The error log can be shown below:

`Traceback (most recent call last):`
  `File "/home/jasper/dev/osiris_science/install/science_servers/lib/science_servers/lowering_platform_server", line 33, in <module>`
    `sys.exit(load_entry_point('science-servers', 'console_scripts', 'lowering_platform_server')())`
  `File "/home/jasper/dev/osiris_science/build/science_servers/science_servers/lowering_platform_server.py", line 8, in main
    boot(LoweringPlatformServer())`
  `File "/home/jasper/dev/osiris_science/build/science_servers/science_servers/template_servers.py", line 159, in __init__
    self.driver = TicUSB()`
  `File "/home/jasper/.local/lib/python3.8/site-packages/ticlib/ticlib.py", line 650, in __init__`
    `self.usb.set_configuration()`
`AttributeError: 'generator' object has no attribute 'set_configuration'`
